import React, { useState } from 'react'
import { X, Download } from 'lucide-react'

const TITLES = [
  'Senior', 'Lead', 'Principal', 'Staff', 'Distinguished'
]

function randomFrom(arr) {
  return arr[Math.floor(Math.random() * arr.length)]
}

export default function MockOfferLetter({ session, score, onClose }) {
  const title    = randomFrom(TITLES)
  const salary   = (Math.floor(Math.random() * 40 + 80) * 1000).toLocaleString()
  const today    = new Date().toLocaleDateString('en-IN', { day:'numeric', month:'long', year:'numeric' })
  const joinDate = new Date(Date.now() + 30*24*60*60*1000).toLocaleDateString('en-IN', { day:'numeric', month:'long', year:'numeric' })

  function downloadLetter() {
    import('jspdf').then(({ default: jsPDF }) => {
      const doc = new jsPDF()
      doc.setFillColor(10,10,15)
      doc.rect(0,0,210,297,'F')
      doc.setFontSize(24); doc.setFont('helvetica','bold'); doc.setTextColor(255,77,28)
      doc.text(session.company.toUpperCase(), 15, 25)
      doc.setFontSize(10); doc.setTextColor(139,139,160)
      doc.text(`${today}`, 15, 35)
      doc.setFontSize(14); doc.setFont('helvetica','bold'); doc.setTextColor(232,232,240)
      doc.text('OFFER OF EMPLOYMENT', 15, 50)
      doc.setFontSize(11); doc.setFont('helvetica','normal'); doc.setTextColor(232,232,240)
      const body = [
        `Dear Candidate,`,
        ``,
        `We are thrilled to offer you the position of ${title} ${session.role} at ${session.company}.`,
        ``,
        `Based on your outstanding interview performance (Nervousness Score: ${score}/100),`,
        `we believe you are an exceptional fit for our team.`,
        ``,
        `Position: ${title} ${session.role}`,
        `Start Date: ${joinDate}`,
        `Compensation: ₹${salary} per annum`,
        ``,
        `This is a mock offer generated by Unflinch to celebrate your great performance.`,
        `Keep practising and the real one is just around the corner!`,
        ``,
        `Congratulations and welcome aboard (in spirit)!`,
        ``,
        `Warm regards,`,
        `The Hiring Team`,
        session.company,
      ]
      let y = 65
      body.forEach(line => {
        doc.text(line, 15, y)
        y += 8
        if (y > 270) { doc.addPage(); y = 20 }
      })
      doc.save(`mock-offer-${session.company}.pdf`.replace(/\s+/g,'-').toLowerCase())
    })
  }

  return (
    <div className="fixed inset-0 bg-obsidian/95 backdrop-blur-sm z-50 flex items-center justify-center p-6 animate-fade-in">
      <div className="max-w-md w-full animate-slide-up">
        <div className="card border-jade/40 bg-carbon relative">
          <button onClick={onClose} className="absolute top-4 right-4 text-mist hover:text-chalk">
            <X size={18} />
          </button>

          <div className="text-center mb-6">
            <div className="text-4xl mb-2">🎉</div>
            <p className="text-jade text-xs uppercase tracking-widest font-mono">Mock Offer Letter</p>
            <h2 className="heading-display text-3xl text-chalk mt-1">Congratulations!</h2>
            <p className="text-mist text-sm mt-2">
              You scored <span className="text-jade font-mono font-bold">{score}/100</span> nervousness — that's impressive!
            </p>
          </div>

          {/* Letter preview */}
          <div className="bg-obsidian rounded-xl p-5 mb-6 border border-steel/50 font-mono text-xs leading-relaxed">
            <div className="text-ember font-bold text-base mb-1">{session.company.toUpperCase()}</div>
            <div className="text-mist mb-4">{today}</div>
            <div className="text-chalk font-bold mb-3">OFFER OF EMPLOYMENT</div>
            <div className="text-chalk/80 space-y-2">
              <p>Dear Candidate,</p>
              <p>We are thrilled to offer you the position of <span className="text-jade">{title} {session.role}</span> at <span className="text-ember">{session.company}</span>.</p>
              <p>Compensation: <span className="text-amber">₹{salary} p.a.</span></p>
              <p>Start Date: <span className="text-azure">{joinDate}</span></p>
              <p className="text-mist text-xs italic mt-3">*This is a mock offer by Unflinch 🎭</p>
            </div>
          </div>

          <div className="flex gap-3">
            <button className="btn-secondary flex-1 flex items-center justify-center gap-2" onClick={downloadLetter}>
              <Download size={16} /> Download PDF
            </button>
            <button className="btn-primary flex-1" onClick={onClose}>
              Keep Practising →
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}