import React, { useEffect, useState, useRef } from 'react'
import { api } from '../lib/api'
import { NavBar, ScoreRing, Spinner, Toast } from '../components/UI'
import { Download, LayoutDashboard, Sparkles, Trophy, AlertCircle, Info, Target, Calendar, CheckCircle2 } from 'lucide-react'
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts'

// ── Confetti (same as dashboard) ─────────────────────────────
function Confetti({ active }) {
  const canvasRef = useRef(null)
  const animRef   = useRef(null)
  useEffect(() => {
    if (!active) return
    const canvas = canvasRef.current
    if (!canvas) return
    const ctx = canvas.getContext('2d')
    canvas.width = window.innerWidth
    canvas.height = window.innerHeight
    const pieces = Array.from({ length: 140 }, () => ({
      x: Math.random() * canvas.width,
      y: Math.random() * -canvas.height,
      w: 8 + Math.random() * 8, h: 4 + Math.random() * 4,
      color: ['#FF4D1C','#FF8C42','#00E5A0','#4A9EFF','#8B5CF6'][Math.floor(Math.random()*5)],
      rot: Math.random() * 360, vx: (Math.random()-0.5)*3,
      vy: 2+Math.random()*4, vr: (Math.random()-0.5)*6,
    }))
    let frame = 0
    const draw = () => {
      ctx.clearRect(0,0,canvas.width,canvas.height)
      pieces.forEach(p => {
        p.x+=p.vx; p.y+=p.vy; p.rot+=p.vr
        ctx.save(); ctx.translate(p.x,p.y); ctx.rotate(p.rot*Math.PI/180)
        ctx.fillStyle=p.color; ctx.fillRect(-p.w/2,-p.h/2,p.w,p.h); ctx.restore()
      })
      frame++
      if (frame < 220) animRef.current = requestAnimationFrame(draw)
      else ctx.clearRect(0,0,canvas.width,canvas.height)
    }
    animRef.current = requestAnimationFrame(draw)
    return () => cancelAnimationFrame(animRef.current)
  }, [active])
  if (!active) return null
  return <canvas ref={canvasRef} className="fixed inset-0 pointer-events-none z-50" style={{width:'100vw',height:'100vh'}} />
}

function generatePDF(session, questions, answers, plan) {
  import('jspdf').then(({ default: jsPDF }) => {
    const doc = new jsPDF()
    const margin = 15
    let y = margin
    const line = (text, size=11, bold=false, color=[230,230,240]) => {
      doc.setFontSize(size); doc.setFont('helvetica', bold?'bold':'normal')
      doc.setTextColor(...color); doc.text(text, margin, y)
      y += size*0.6+3; if(y>280){doc.addPage();y=margin}
    }
    const gap = (n=6) => { y+=n }
    doc.setFillColor(10,10,15); doc.rect(0,0,210,297,'F')
    doc.setFontSize(28); doc.setFont('helvetica','bold'); doc.setTextColor(255,77,28)
    doc.text('UNFLINCH', margin, 24)
    doc.setFontSize(11); doc.setTextColor(139,139,160)
    doc.text('AI Interview Prep Report', margin, 32)
    y=44
    line(`Company: ${session.company}   Role: ${session.role}`, 11, true)
    line(`Round: ${session.round}   Date: ${new Date(session.created_at).toLocaleDateString()}`, 10, false, [139,139,160])
    line(`Overall Nervousness: ${session.overall_nervousness??'—'} / 100`, 11, true, [255,77,28])
    gap(8); line('QUESTION BREAKDOWN', 13, true, [255,77,28])
    doc.setDrawColor(42,42,60); doc.line(margin, y, 210-margin, y); y+=5
    questions.forEach((q,i) => {
      const ans = answers.find(a=>a.question_id===q.id)
      gap(4); line(`Q${i+1}: ${q.question_text}`, 10, true, [232,232,240])
      if(ans){
        line(`  Score: ${ans.nervousness_score}  Fillers: ${ans.filler_count}  Pauses: ${ans.pause_count}  Rate: ${ans.speech_rate} w/s`, 9, false, [139,139,160])
        line(`  Tip: ${ans.improvement_tip}`, 9, false, [74,158,255])
        if(ans.transcript){
          const wrapped = doc.splitTextToSize(`  Transcript: ${ans.transcript}`, 180)
          wrapped.forEach(l=>line(l,8,false,[139,139,160]))
        }
      }
    })
    gap(10); line('IMPROVEMENT PLAN', 13, true, [0,229,160])
    doc.line(margin,y,210-margin,y); y+=5; gap(4)
    doc.splitTextToSize(plan,180).forEach(l=>line(l,10,false,[232,232,240]))
    gap(8); line('Generated by Unflinch · unflinch.app', 8, false, [42,42,60])
    doc.save(`unflinch-${session.company}-${session.role}.pdf`.replace(/\s+/g,'-').toLowerCase())
  })
}

export default function SummaryPage({ navigate, onSignOut, user, params }) {
  const { sessionId, readOnly } = params || {}
  const [session, setSession]     = useState(null)
  const [questions, setQuestions] = useState([])
  const [answers, setAnswers]     = useState([])
  const [plan, setPlan]           = useState(null)
  const [loading, setLoading]     = useState(true)
  const [planLoading, setPlanLoad]= useState(false)
  const [saved, setSaved]         = useState(false)
  const [toast, setToast]         = useState(null)
  const [confetti, setConfetti]   = useState(false)
  const [expandBest, setExpandBest]   = useState(false)
  const [expandWorst, setExpandWorst] = useState(false)

  useEffect(() => {
    if (!sessionId) return navigate('dashboard')
    api.getSession(sessionId)
      .then(d => {
        setSession(d.session)
        setQuestions(d.questions || [])
        setAnswers(d.answers || [])
        // Fire confetti for good scores
        const avg = d.answers?.length
          ? d.answers.reduce((a,b)=>a+(b.nervousness_score||0),0)/d.answers.length : 100
        if (avg < 40) {
          setTimeout(()=>setConfetti(true), 500)
          setTimeout(()=>setConfetti(false), 4500)
        }
        setPlanLoad(true)
        return api.generateImprovementPlan(sessionId)
      })
      .then(d => setPlan(d || null))
      .catch(err => setToast({ message: err.message, type: 'error' }))
      .finally(() => { setLoading(false); setPlanLoad(false) })
  }, [sessionId])

  async function handleSave() {
    try {
      await api.saveSession(sessionId)
      setSaved(true)
      setToast({ message: 'Session saved!', type: 'success' })
    } catch (err) {
      setToast({ message: err.message, type: 'error' })
    }
  }

  if (loading) return (
    <div className="min-h-screen bg-obsidian flex items-center justify-center">
      <Spinner className="w-8 h-8 text-mist" />
    </div>
  )

  const avgScore = answers.length
    ? answers.reduce((a,b)=>a+(b.nervousness_score||0),0)/answers.length : 0
  const scoreColorClass = avgScore < 35 ? 'text-jade' : avgScore < 60 ? 'text-amber' : 'text-ember'

  // Best and worst answers
  const sorted    = [...answers].filter(a=>a.nervousness_score!=null).sort((a,b)=>a.nervousness_score-b.nervousness_score)
  const bestAns   = sorted[0]
  const worstAns  = sorted[sorted.length-1]
  const bestQ     = bestAns  ? questions.find(q=>q.id===bestAns.question_id)  : null
  const worstQ    = worstAns ? questions.find(q=>q.id===worstAns.question_id) : null

  // Chart data
  const chartData = answers.map((a, i) => ({
    name: `Q${i + 1}`,
    confidence: a.confidence_score ?? 0
  }))
  const isTrendingUp = chartData.length > 1 && chartData[chartData.length - 1].confidence >= chartData[0].confidence
  const chartColor = isTrendingUp ? '#00E5A0' : '#FF4D1C'

  return (
    <>
      <Confetti active={confetti} />
      <NavBar onSignOut={onSignOut} userName={user?.email} />

      <main className="min-h-screen bg-obsidian px-4 py-8 md:px-8">
        <div className="max-w-3xl mx-auto">

          {/* Header */}
          <div className="mb-8 animate-fade-in">
            <p className="text-mist text-xs uppercase tracking-widest font-mono mb-1">Session Complete</p>
            <h1 className="heading-display text-5xl">
              <span className="gradient-text">Results</span>
            </h1>
            {session && (
              <p className="text-mist text-sm mt-2">
                {session.role} at {session.company} · {session.round}
              </p>
            )}
          </div>

          {/* Overall score */}
          <div className="card flex items-center gap-6 mb-6 animate-slide-up">
            <ScoreRing score={parseFloat(avgScore.toFixed(1))} size={96} />
            <div>
              <p className="text-mist text-xs uppercase tracking-widest font-mono">Overall Nervousness</p>
              <p className={`text-4xl font-mono font-bold ${scoreColorClass} mt-1`}>
                {avgScore.toFixed(1)} <span className="text-mist text-lg font-normal">/ 100</span>
              </p>
              <p className="text-mist text-sm mt-1">
                {avgScore < 35 ? '🎉 Excellent! You were calm & confident!'
                 : avgScore < 60 ? '🟡 Good effort — moderate nerves detected'
                 : '🔴 High nervousness — keep practising!'}
              </p>
            </div>
          </div>

          {/* Best vs Worst comparison */}
          {bestAns && worstAns && bestAns.id !== worstAns.id && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6 animate-slide-up">
              {/* Best */}
              <div className="card border-jade/30 cursor-pointer" onClick={()=>setExpandBest(v=>!v)}>
                <div className="flex items-center gap-2 mb-2">
                  <Trophy size={14} className="text-jade" />
                  <span className="text-jade text-xs uppercase tracking-widest font-mono">Best Answer</span>
                  <span className="text-jade font-mono font-bold ml-auto">{bestAns.nervousness_score}</span>
                </div>
                <p className="text-chalk text-sm line-clamp-2">{bestQ?.question_text}</p>
                {expandBest && (
                  <div className="mt-3 pt-3 border-t border-steel">
                    <p className="text-mist text-xs mb-1">Transcript:</p>
                    <p className="text-chalk/80 text-xs leading-relaxed">{bestAns.transcript || '—'}</p>
                    <div className="flex gap-4 mt-2 text-xs text-mist font-mono">
                      <span>Fillers: {bestAns.filler_count}</span>
                      <span>Pauses: {bestAns.pause_count}</span>
                      <span>Rate: {bestAns.speech_rate} w/s</span>
                    </div>
                  </div>
                )}
                <p className="text-mist text-xs mt-2">{expandBest ? '▲ collapse' : '▼ expand'}</p>
              </div>

              {/* Worst */}
              <div className="card border-ember/30 cursor-pointer" onClick={()=>setExpandWorst(v=>!v)}>
                <div className="flex items-center gap-2 mb-2">
                  <AlertCircle size={14} className="text-ember" />
                  <span className="text-ember text-xs uppercase tracking-widest font-mono">Needs Work</span>
                  <span className="text-ember font-mono font-bold ml-auto">{worstAns.nervousness_score}</span>
                </div>
                <p className="text-chalk text-sm line-clamp-2">{worstQ?.question_text}</p>
                {expandWorst && (
                  <div className="mt-3 pt-3 border-t border-steel">
                    <p className="text-mist text-xs mb-1">Tip:</p>
                    <p className="text-chalk/80 text-xs leading-relaxed">{worstAns.improvement_tip || '—'}</p>
                    <div className="flex gap-4 mt-2 text-xs text-mist font-mono">
                      <span>Fillers: {worstAns.filler_count}</span>
                      <span>Pauses: {worstAns.pause_count}</span>
                      <span>Rate: {worstAns.speech_rate} w/s</span>
                    </div>
                  </div>
                )}
                <p className="text-mist text-xs mt-2">{expandWorst ? '▲ collapse' : '▼ expand'}</p>
              </div>
            </div>
          )}

          {/* Question breakdown table */}
          <div className="card mb-6 overflow-hidden animate-slide-up p-0">
            <div className="px-6 py-4 border-b border-steel">
              <p className="text-mist text-xs uppercase tracking-widest font-mono">Question Breakdown</p>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-steel/50">
                    {['#','Question','Score','Fillers','Pauses','Top Tip'].map(h=>(
                      <th key={h} className="text-left text-mist text-xs font-mono uppercase tracking-wider px-4 py-3
                        first:pl-6 last:hidden md:last:table-cell">{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {questions.map((q,i) => {
                    const ans = answers.find(a=>a.question_id===q.id)
                    const sc  = ans?.nervousness_score ?? null
                    const scClass = sc===null ? 'text-mist' : sc<35 ? 'text-jade' : sc<60 ? 'text-amber' : 'text-ember'
                    return (
                      <tr key={q.id} className="border-b border-steel/30 hover:bg-steel/20 transition-colors">
                        <td className="pl-6 pr-2 py-4 text-mist font-mono">{i+1}</td>
                        <td className="px-3 py-4 text-chalk max-w-xs">
                          <span className="line-clamp-2 text-sm">{q.question_text}</span>
                        </td>
                        <td className="px-3 py-4">
                          <span className={`font-mono font-semibold ${scClass}`}>{sc?.toFixed(0)??'—'}</span>
                        </td>
                        <td className="px-3 py-4 text-chalk font-mono text-center">{ans?.filler_count??'—'}</td>
                        <td className="px-3 py-4 text-chalk font-mono text-center">{ans?.pause_count??'—'}</td>
                        <td className="px-3 py-4 text-mist text-xs max-w-xs hidden md:table-cell">
                          <span className="line-clamp-2">{ans?.improvement_tip??'—'}</span>
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          </div>

          {/* Know Before You Go */}
          {session && session.session_context && session.session_context.length > 0 && (
            <div className="card mb-6 border-azure/30 animate-slide-up">
              <div className="flex items-center gap-2 mb-4">
                <Info size={16} className="text-azure" />
                <p className="text-azure text-xs uppercase tracking-widest font-mono">Know Before You Go</p>
              </div>
              <ul className="text-chalk text-sm space-y-2 list-disc pl-5">
                {session.session_context.map((point, idx) => (
                  <li key={idx} className="leading-relaxed">{point}</li>
                ))}
              </ul>
            </div>
          )}

          {/* Confidence Trend Chart */}
          {chartData.length > 0 && (
            <div className="card mb-6 border-steel/30 animate-slide-up">
              <p className="text-mist text-xs uppercase tracking-widest font-mono mb-4">Confidence Trend</p>
              <div className="h-64 w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={chartData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#2A2A35" />
                    <XAxis dataKey="name" stroke="#8B8BA0" tick={{fontSize: 12}} />
                    <YAxis stroke="#8B8BA0" tick={{fontSize: 12}} domain={[0, 100]} />
                    <Tooltip 
                      contentStyle={{ backgroundColor: '#1E1E28', border: '1px solid #2A2A35', borderRadius: '8px' }}
                      itemStyle={{ color: '#E8E8F0' }}
                    />
                    <Line type="monotone" dataKey="confidence" stroke={chartColor} strokeWidth={3} dot={{r: 4, fill: chartColor}} />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </div>
          )}

          {/* Improvement plan */}
          <div className="card mb-8 border-jade/30 animate-slide-up">
            <div className="flex items-center gap-2 mb-4">
              <Sparkles size={16} className="text-jade" />
              <p className="text-jade text-xs uppercase tracking-widest font-mono">AI Improvement Plan</p>
            </div>
            {planLoading ? (
              <div className="flex items-center gap-3">
                <Spinner className="w-4 h-4 text-mist" />
                <span className="text-mist text-sm">Generating your plan…</span>
              </div>
            ) : plan ? (
              <div className="flex flex-col gap-6">
                <div>
                  <h4 className="text-chalk font-semibold mb-2">Overall Verdict</h4>
                  <p className="text-mist text-sm leading-relaxed">{plan.overall_verdict}</p>
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="bg-carbon p-4 rounded-xl border border-jade/20">
                    <div className="flex items-center gap-2 mb-3">
                      <Trophy size={14} className="text-jade" />
                      <h4 className="text-jade text-xs uppercase tracking-widest font-mono">Top Strengths</h4>
                    </div>
                    <ul className="text-mist text-sm space-y-1">
                      {plan.top_strengths?.map((s, i) => <li key={i}>• {s}</li>)}
                    </ul>
                  </div>
                  <div className="bg-carbon p-4 rounded-xl border border-ember/20">
                    <div className="flex items-center gap-2 mb-3">
                      <Target size={14} className="text-ember" />
                      <h4 className="text-ember text-xs uppercase tracking-widest font-mono">Critical Gaps</h4>
                    </div>
                    <ul className="text-mist text-sm space-y-1">
                      {plan.critical_gaps?.map((g, i) => <li key={i}>• {g}</li>)}
                    </ul>
                  </div>
                </div>

                {plan.weekly_plan && plan.weekly_plan.length > 0 && (
                  <div>
                    <div className="flex items-center gap-2 mb-3">
                      <Calendar size={14} className="text-violet" />
                      <h4 className="text-violet text-xs uppercase tracking-widest font-mono">Weekly Drill Plan</h4>
                    </div>
                    <div className="space-y-3">
                      {plan.weekly_plan.map((wp, i) => (
                        <div key={i} className="flex gap-3 bg-carbon/50 p-3 rounded-lg border border-steel/30">
                          <div className="w-8 h-8 rounded-full bg-violet/10 text-violet flex items-center justify-center font-mono text-xs shrink-0">
                            W{wp.week}
                          </div>
                          <div>
                            <p className="text-chalk text-sm font-medium">{wp.focus}</p>
                            <p className="text-mist text-xs mt-1">{wp.action}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {plan.company_specific_tip && (
                  <div className="bg-azure/5 p-4 rounded-xl border border-azure/30 mt-2">
                    <div className="flex items-center gap-2 mb-2">
                      <Info size={14} className="text-azure" />
                      <h4 className="text-azure text-xs uppercase tracking-widest font-mono">{session?.company} Tip</h4>
                    </div>
                    <p className="text-chalk text-sm leading-relaxed">{plan.company_specific_tip}</p>
                  </div>
                )}
              </div>
            ) : (
              <p className="text-mist text-sm">Could not generate plan.</p>
            )}
          </div>

          {/* Action buttons */}
          <div className="flex flex-col sm:flex-row gap-3 animate-fade-in">
            {!readOnly && !saved && (
              <button className="btn-primary flex items-center justify-center gap-2" onClick={handleSave}>
                Save Session
              </button>
            )}
            <button
              className="btn-secondary flex items-center justify-center gap-2"
              onClick={() => generatePDF(session, questions, answers, plan)}
            >
              <Download size={16} /> Download PDF
            </button>
            <button
              className="btn-ghost flex items-center justify-center gap-2"
              onClick={() => navigate('dashboard')}
            >
              <LayoutDashboard size={16} /> Back to Dashboard
            </button>
          </div>
        </div>
      </main>

      {toast && <Toast message={toast.message} type={toast.type} onClose={() => setToast(null)} />}
    </>
  )
}