import React, { useEffect, useState } from 'react'
import { api } from '../lib/api'
import { NavBar, ScoreRing, Spinner, Toast } from '../components/UI'
import { Download, LayoutDashboard, Sparkles } from 'lucide-react'

function generatePDF(session, questions, answers, plan) {
  // Dynamic import to keep bundle lean
  import('jspdf').then(({ default: jsPDF }) => {
    const doc = new jsPDF()
    const margin = 15
    let y = margin

    const line = (text, size = 11, bold = false, color = [230, 230, 240]) => {
      doc.setFontSize(size)
      doc.setFont('helvetica', bold ? 'bold' : 'normal')
      doc.setTextColor(...color)
      doc.text(text, margin, y)
      y += size * 0.6 + 3
      if (y > 280) { doc.addPage(); y = margin }
    }

    const gap = (n = 6) => { y += n }

    // Header
    doc.setFillColor(10, 10, 15)
    doc.rect(0, 0, 210, 297, 'F')
    doc.setFontSize(28)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(255, 77, 28)
    doc.text('UNFLINCH', margin, 24)
    doc.setFontSize(11)
    doc.setTextColor(139, 139, 160)
    doc.text('AI Interview Prep Report', margin, 32)

    y = 44
    line(`Company: ${session.company}   Role: ${session.role}`, 11, true)
    line(`Round: ${session.round}   Date: ${new Date(session.created_at).toLocaleDateString()}`, 10, false, [139, 139, 160])
    line(`Overall Nervousness: ${session.overall_nervousness ?? '—'} / 100`, 11, true, [255, 77, 28])

    gap(8)
    line('QUESTION BREAKDOWN', 13, true, [255, 77, 28])
    doc.setDrawColor(42, 42, 60)
    doc.line(margin, y, 210 - margin, y)
    y += 5

    questions.forEach((q, i) => {
      const ans = answers.find(a => a.question_id === q.id)
      gap(4)
      line(`Q${i + 1}: ${q.question_text}`, 10, true, [232, 232, 240])
      if (ans) {
        line(`  Nervousness: ${ans.nervousness_score}  Fillers: ${ans.filler_count}  Pauses: ${ans.pause_count}  Rate: ${ans.speech_rate} w/s`, 9, false, [139, 139, 160])
        line(`  Tip: ${ans.improvement_tip}`, 9, false, [74, 158, 255])
        if (ans.transcript) {
          const wrapped = doc.splitTextToSize(`  Transcript: ${ans.transcript}`, 180)
          wrapped.forEach(l => line(l, 8, false, [139, 139, 160]))
        }
      }
    })

    gap(10)
    line('IMPROVEMENT PLAN', 13, true, [0, 229, 160])
    doc.line(margin, y, 210 - margin, y); y += 5
    gap(4)
    const planLines = doc.splitTextToSize(plan, 180)
    planLines.forEach(l => line(l, 10, false, [232, 232, 240]))

    gap(8)
    line('Generated by Unflinch · unflinch.app', 8, false, [42, 42, 60])

    doc.save(`unflinch-${session.company}-${session.role}.pdf`.replace(/\s+/g, '-').toLowerCase())
  })
}

export default function SummaryPage({ navigate, onSignOut, user, params }) {
  const { sessionId, readOnly } = params || {}

  const [session, setSession]     = useState(null)
  const [questions, setQuestions] = useState([])
  const [answers, setAnswers]     = useState([])
  const [plan, setPlan]           = useState('')
  const [loading, setLoading]     = useState(true)
  const [planLoading, setPlanLoad]= useState(false)
  const [saved, setSaved]         = useState(false)
  const [toast, setToast]         = useState(null)

  useEffect(() => {
    if (!sessionId) return navigate('dashboard')
    api.getSession(sessionId)
      .then(d => {
        setSession(d.session)
        setQuestions(d.questions || [])
        setAnswers(d.answers || [])
        // Auto-generate plan
        setPlanLoad(true)
        return api.generateImprovementPlan(sessionId)
      })
      .then(d => setPlan(d.plan || ''))
      .catch(err => setToast({ message: err.message, type: 'error' }))
      .finally(() => { setLoading(false); setPlanLoad(false) })
  }, [sessionId])

  async function handleSave() {
    try {
      await api.saveSession(sessionId)
      setSaved(true)
      setToast({ message: 'Session saved!', type: 'success' })
    } catch (err) {
      setToast({ message: err.message, type: 'error' })
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-obsidian flex items-center justify-center">
        <Spinner className="w-8 h-8 text-mist" />
      </div>
    )
  }

  const avgScore = answers.length
    ? (answers.reduce((a, b) => a + (b.nervousness_score || 0), 0) / answers.length).toFixed(1)
    : 0

  const scoreColor = avgScore < 35 ? 'text-jade' : avgScore < 60 ? 'text-amber' : 'text-ember'

  return (
    <>
      <NavBar onSignOut={onSignOut} userName={user?.phone} />
      <main className="min-h-screen bg-obsidian px-4 py-8 md:px-8">
        <div className="max-w-3xl mx-auto">

          {/* Header */}
          <div className="mb-8 animate-fade-in">
            <p className="text-mist text-xs uppercase tracking-widest font-mono mb-1">Session Complete</p>
            <h1 className="heading-display text-5xl">
              <span className="gradient-text">Results</span>
            </h1>
            {session && (
              <p className="text-mist text-sm mt-2">
                {session.role} at {session.company} · {session.round}
              </p>
            )}
          </div>

          {/* Overall score */}
          <div className="card flex items-center gap-6 mb-6 animate-slide-up">
            <ScoreRing score={parseFloat(avgScore)} size={96} />
            <div>
              <p className="text-mist text-xs uppercase tracking-widest font-mono">Overall Nervousness</p>
              <p className={`text-4xl font-mono font-bold ${scoreColor} mt-1`}>
                {avgScore} <span className="text-mist text-lg font-normal">/ 100</span>
              </p>
              <p className="text-mist text-sm mt-1">
                {avgScore < 35 ? '🟢 Calm & confident'
                 : avgScore < 60 ? '🟡 Moderate nerves'
                 : '🔴 High nervousness — keep practising!'}
              </p>
            </div>
          </div>

          {/* Question breakdown table */}
          <div className="card mb-6 overflow-hidden animate-slide-up p-0">
            <div className="px-6 py-4 border-b border-steel">
              <p className="text-mist text-xs uppercase tracking-widest font-mono">Question Breakdown</p>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-steel/50">
                    <th className="text-left text-mist text-xs font-mono uppercase tracking-wider px-6 py-3">#</th>
                    <th className="text-left text-mist text-xs font-mono uppercase tracking-wider px-3 py-3">Question</th>
                    <th className="text-center text-mist text-xs font-mono uppercase tracking-wider px-3 py-3">Score</th>
                    <th className="text-center text-mist text-xs font-mono uppercase tracking-wider px-3 py-3 hidden md:table-cell">Fillers</th>
                    <th className="text-center text-mist text-xs font-mono uppercase tracking-wider px-3 py-3 hidden md:table-cell">Pauses</th>
                    <th className="text-left text-mist text-xs font-mono uppercase tracking-wider px-3 py-3">Top Tip</th>
                  </tr>
                </thead>
                <tbody>
                  {questions.map((q, i) => {
                    const ans = answers.find(a => a.question_id === q.id)
                    const sc = ans?.nervousness_score ?? null
                    const scColor = sc === null ? 'text-mist'
                      : sc < 35 ? 'text-jade' : sc < 60 ? 'text-amber' : 'text-ember'
                    return (
                      <tr key={q.id} className="border-b border-steel/30 hover:bg-steel/20 transition-colors">
                        <td className="px-6 py-4 text-mist font-mono">{i + 1}</td>
                        <td className="px-3 py-4 text-chalk max-w-xs">
                          <span className="line-clamp-2">{q.question_text}</span>
                        </td>
                        <td className="px-3 py-4 text-center">
                          <span className={`font-mono font-semibold ${scColor}`}>
                            {sc?.toFixed(0) ?? '—'}
                          </span>
                        </td>
                        <td className="px-3 py-4 text-center text-chalk font-mono hidden md:table-cell">
                          {ans?.filler_count ?? '—'}
                        </td>
                        <td className="px-3 py-4 text-center text-chalk font-mono hidden md:table-cell">
                          {ans?.pause_count ?? '—'}
                        </td>
                        <td className="px-3 py-4 text-mist text-xs max-w-xs">
                          <span className="line-clamp-2">{ans?.improvement_tip ?? '—'}</span>
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          </div>

          {/* Improvement plan */}
          <div className="card mb-8 border-jade/30 animate-slide-up">
            <div className="flex items-center gap-2 mb-4">
              <Sparkles size={16} className="text-jade" />
              <p className="text-jade text-xs uppercase tracking-widest font-mono">AI Improvement Plan</p>
            </div>
            {planLoading ? (
              <div className="flex items-center gap-3">
                <Spinner className="w-4 h-4 text-mist" />
                <span className="text-mist text-sm">Generating your plan…</span>
              </div>
            ) : (
              <div className="text-chalk text-sm leading-relaxed whitespace-pre-line">{plan}</div>
            )}
          </div>

          {/* Action buttons */}
          <div className="flex flex-col sm:flex-row gap-3 animate-fade-in">
            {!readOnly && !saved && (
              <button className="btn-primary flex items-center justify-center gap-2" onClick={handleSave}>
                Save Session
              </button>
            )}
            <button
              className="btn-secondary flex items-center justify-center gap-2"
              onClick={() => generatePDF(session, questions, answers, plan)}
            >
              <Download size={16} />
              Download PDF
            </button>
            <button
              className="btn-ghost flex items-center justify-center gap-2"
              onClick={() => navigate('dashboard')}
            >
              <LayoutDashboard size={16} />
              Back to Dashboard
            </button>
          </div>
        </div>
      </main>

      {toast && <Toast message={toast.message} type={toast.type} onClose={() => setToast(null)} />}
    </>
  )
}
